export enum Ability {
  STRENGTH,
  DEXTERITY,
  CONSTITUTION,
  INTELLIGENCE,
  WISDOM,
  CHARISMA,
};

export enum AbilityCheck {
  ACROBATICS,
  ANIMAL_HANDLING,
  ARCANA,
  ATHLETICS,
  DECEPTION,
  HISTORY,
  INSIGHT,
  INTIMIDATION,
  INVESTIGATION,
  MEDICINE,
  NATURE,
  PERCEPTION,
  PERFORMANCE,
  PERSUASION,
  RELIGION,
  SLEIGHT_OF_HAND,
  STEALTH,
  SURVIVAL,
};

export const AbilityChecks = [
  AbilityCheck.ACROBATICS,
  AbilityCheck.ANIMAL_HANDLING,
  AbilityCheck.ARCANA,
  AbilityCheck.ATHLETICS,
  AbilityCheck.DECEPTION,
  AbilityCheck.HISTORY,
  AbilityCheck.INSIGHT,
  AbilityCheck.INTIMIDATION,
  AbilityCheck.INVESTIGATION,
  AbilityCheck.MEDICINE,
  AbilityCheck.NATURE,
  AbilityCheck.PERCEPTION,
  AbilityCheck.PERFORMANCE,
  AbilityCheck.PERSUASION,
  AbilityCheck.RELIGION,
  AbilityCheck.SLEIGHT_OF_HAND,
  AbilityCheck.STEALTH,
  AbilityCheck.SURVIVAL,
];